"""
Drug Discovery API — shared configuration
Set PARTNER_API_KEY as an environment variable before running any example:
    export PARTNER_API_KEY="your_key_here"   # Linux / macOS
    set PARTNER_API_KEY=your_key_here        # Windows CMD
    $env:PARTNER_API_KEY="your_key_here"     # Windows PowerShell
"""

import os

BASE_URL = "https://drug-discovery-orchestrator.fly.dev"

PARTNER_API_KEY = os.getenv("PARTNER_API_KEY", "YOUR_PARTNER_API_KEY")

HEADERS = {
    "X-API-Key": PARTNER_API_KEY,
    "Content-Type": "application/json",
}

# Molecule used across examples
ASPIRIN_SMILES       = "CC(=O)Oc1ccccc1C(=O)O"
IBUPROFEN_SMILES     = "CC(C)Cc1ccc(cc1)C(C)C(=O)O"
CELECOXIB_SMILES     = "CC1=CC=C(C=C1)C2=CC(=NN2C3=CC=C(C=C3)S(=O)(=O)N)C(F)(F)F"
IBUPROFEN_MASKED     = "CC(C)Cc1ccc(C(C)<mask>C(=O)O)cc1"

# Protein sequences used across examples
COX2_SEQUENCE = (
    "MLARALLLCAVLALSHTANPCCSHPCQNRGVCMSVGFDQYKCDCTRTGFYGENCSTPEFLT"
    "RIKLFLKPTPNTVHYILTHFKGFWNVVNNIPFLRNAIMSYVLTSRSHLIDSPPTYNADYGY"
    "KSWEAFSNLSYYTRALPPVPDDCPTPLGVKGKKQLPDSNEIVEKLLLRRKFIPD"
)

CDK2_SEQUENCE = (
    "MENFQKVEKIGEGTYGVVYKARNKLTGEVVALKKIRLDTETEGVPSTAIREISLLKELNHPN"
    "IVKLLDVIHTENKLYLVFEFLHQDLKKFMDASALTGIPLPLIKSYLFQLLQGLAFCHSHRV"
    "LHRDLKPQNLLINTEGAIKLADFGLARAFGVPVRTYTHEVVTLWYRAPEILLGCKYYSTAVD"
    "IWSLGCIFAEMVTRRALFPGDSEIDQLFSRILLGTPNEAIWPDIVYLPDFKPSFPQWRRKDL"
    "SQVVPSLDPRGIDLLDKLLAKNLVEDAHSLTSGSTPTLSSSAGSVTPMSTKVLV"
)
